name: "[CI] Continuous Integration"

# sempre que tiver um commit ou um PR for aberto
on:
  pull_request:
    types: [opened, synchronize]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      ## [Common_CI_Steps]
      - uses: actions/checkout@v3
      ## =================
      - name: "Install Dependencies"
        run: "npm install"
      - name: "Lint"
        run: "npm run lint"
  test:
    runs-on: ubuntu-latest
    container: cypress/browsers:node18.12.0-chrome107
    steps:
      ## [Common_CI_Steps]
      - uses: actions/checkout@v3
      ## =================
      - name: "Install Dependencies"
        run: "npm install"
      - name: "Grant access to folder ./core/db"
        run: "sudo chmod -R 777 ./core/db"
      - name: "Test - Cypress"
        run: "npm run test"
